apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert-k3s.c-s.au-staging
  namespace: letsencrypt-wildcard-cert
spec:
  secretName: letsencrypt-wildcard-cert-k3s.c-s.au-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "k3s.c-s.au"
    - "*.k3s.c-s.au"
