apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@cs-network.org
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "c-s.au"
          - "cs-network.org"
      dns01:
        cloudflare:
          email: admin@cs-network.org
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
