---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-lb
  namespace: networking
spec:
  ipAddressPools:
    - bgp-pool
  peers:
    - gateway
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: gateway
  namespace: networking
spec:
  peerAddress: 10.0.2.1
  peerASN: 64512
  myASN: 64512
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-pool
  namespace: networking
spec:
  addresses: 10.0.10.0/24
