---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-lb
  namespace: metallb-system
spec:
  ipAddressPools:
    - bgp-pool
  peers:
    - gateway
  aggregationLength: 32
  localPref: 100
