apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      #version: 5.1.x # auto-update to semver bugfixes only
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  valuesFrom:
  - kind: ConfigMap
    name: external-dns-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
