apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-replicator-helm-chart-value-overrides
  namespace: secret-replicator
data:
  values.yaml: |-
    # Default values for secret-replicator.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    image:
      repository: kiwigrid/secret-replicator
      tag: latest #0.2.0 It's 0.1.0 and latest listed in dockerhub. No 0.2.0 anymore
      pullPolicy: IfNotPresent
      ## Specify ImagePullSecrets for Pods
      ## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
      # pullSecrets: myregistrykey

    # csv list of secrets
    secretList: "letsencrypt-wildcard-cert-k3s.c-s.au-production"
    # secretList: "secret1,secret2

    ignoreNamespaces: "kube-system,kube-public"

    # If defined, allow secret-replicator to watch for secrets in _another_ namespace
    secretNamespace: "letsencrypt-wildcard-cert"

    rbac:
      enabled: true

    resources: {}
      # limits:
      #   cpu: 50m
      #   memory: 20Mi
      # requests:
      #   cpu: 20m
      #   memory: 20Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}
